name: Terraform CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      TF_IN_AUTOMATION: true
    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v4

      # Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      # Install tfsec for security scanning
      - name: Install tfsec
        run: |
          curl -s https://raw.githubusercontent.com/aquasecurity/tfsec/master/scripts/install_linux.sh | bash

      # Initialize Terraform (disable backend for CI)
      - name: Terraform Init
        run: terraform init -backend=false

      # Check code formatting
      - name: Terraform Format
        run: terraform fmt -check -recursive

      # Validate Terraform configuration
      - name: Terraform Validate
        run: terraform validate

      # Security Scan
      - name: Security Scan
        run: tfsec .

      # Dry-run plan (no state changes)
      - name: Terraform Plan
        run: terraform plan -lock=false -input=false
